import './styles.css';

const SHOPIFY_URL = 'https://brand-blueprint-studio-wt3ml-abpg4kjq.myshopify.com/api/2025-07/graphql.json';
const SHOPIFY_TOKEN = 'bfedf7bb47b55313afd3bdbc34af856a';
const CART_KEY = 'camille-cart-v3';

const products = [
  {slug:'the-wealth-operating-system',title:'The Wealth Operating System',subtitle:'The weekly money rhythm behind a business that can actually fund your life.',category:'Money & Profit',tier:'Core',price:39,summary:'A complete operating rhythm for personal and business money, so income stops disappearing into guesswork.',included:['The weekly money meeting framework','Income, commitments, and reserves map','Lifestyle affordability worksheet','Spending decision rules','Ninety-day money rhythm tracker'],outcome:'Know what came in, what is committed, what is protected, and what your next financial decision should be.'},
  {slug:'the-profit-clarity-planner',title:'The Profit Clarity Planner',subtitle:'Revenue, costs, reserves, owner pay, and profit in language you can act on.',category:'Money & Profit',tier:'Entry',price:29,summary:'A guided planner that turns business numbers into five clear figures you can review in an afternoon.',included:['Five-figure profit worksheet','Cost of delivery breakdown','Reserve and tax holding guide','Owner pay planner','Quarterly profit review sheet'],outcome:'Leave with a completed profit picture and a defensible owner-pay number.'},
  {slug:'the-premium-offer-architect',title:'The Premium Offer Architect',subtitle:'Turn scattered skill into one focused offer you can explain in a sentence.',category:'Offers & Products',tier:'Premium',price:79,summary:'A structured method for shaping one clear, sellable offer instead of ten half-built ideas.',included:['Buyer fit map','Transformation ladder','Offer architecture canvas','Scope control checklist','Pricing rationale worksheet'],outcome:'Define one premium offer with a clear buyer, transformation, scope, and price.'},
  {slug:'brand-with-weight',title:'Brand With Weight',subtitle:'Positioning, voice, and visual direction that make the business unmistakable.',category:'Brand & Content',tier:'Premium',price:89,summary:'A brand system for women whose thinking is stronger than the way the business currently communicates it.',included:['Brand thesis workbook','Positioning statement builder','Signature method canvas','Voice and language guide','Visual direction board'],outcome:'Build a brand that reads as considered, consistent, and distinctly yours.'},
  {slug:'the-digital-product-studio',title:'The Digital Product Studio',subtitle:'Plan, build, and finish a digital product without losing months to it.',category:'Offers & Products',tier:'Core',price:59,summary:'A production system for turning knowledge into an ebook, workbook, toolkit, or mini course that actually ships.',included:['Format selection guide','Product outline builder','Production sequence plan','Asset and template checklist','Delivery and file setup guide'],outcome:'Move from a strong idea to a finished, deliverable digital product.'},
  {slug:'the-signature-content-system',title:'The Signature Content System',subtitle:'Content that connects to the offer instead of feeding the algorithm.',category:'Brand & Content',tier:'Core',price:49,summary:'A content system built around themes, customer journey, and the offer you are actually selling.',included:['Content pillar builder','Buyer journey map','Signature idea bank','Monthly content rhythm planner','Call-to-action library'],outcome:'Publish fewer, better-placed ideas that lead naturally to your offer.'},
  {slug:'the-calm-launch-playbook',title:'The Calm Launch Playbook',subtitle:'A composed launch with real messaging, timing, and a proper review afterwards.',category:'Sales & Launch',tier:'Premium',price:69,summary:'A full launch plan built on preparation and clear messaging rather than urgency and noise.',included:['Launch runway timeline','Messaging and angle planner','Email sequence outlines','Daily launch-week schedule','Post-launch review framework'],outcome:'Run a repeatable launch without panic, improvisation, or borrowed urgency.'},
  {slug:'the-elevated-sales-page-kit',title:'The Elevated Sales Page Kit',subtitle:'Write a product page that communicates value without a single hype line.',category:'Sales & Launch',tier:'Entry',price:39,summary:'Section-by-section structure and language for a sales page that reads as premium and converts.',included:['Page structure blueprint','Section-by-section prompts','Objection handling bank','Headline patterns','Pre-publish review checklist'],outcome:'Draft a complete sales page that answers the buyer’s questions in the right order.'},
  {slug:'the-solo-ceo-operating-desk',title:'The Solo CEO Operating Desk',subtitle:'Weekly priorities, delivery, sales, and customer care in one calm structure.',category:'CEO Operations',tier:'Premium',price:79,summary:'The operating structure for a woman running everything herself and wanting the week to hold.',included:['Weekly operating rhythm planner','Priority and capacity sheet','Delivery workflows','Customer care standards guide','Monthly business review'],outcome:'Give every essential part of the business a place in the week.'},
];
const house={slug:'the-camille-business-house',title:'The Camille Business House',subtitle:'Ongoing implementation, planning, and company for women building something substantial.',price:29};
let shopifyProducts=[];
let cart=JSON.parse(localStorage.getItem(CART_KEY)||'{"items":[],"cartId":null,"checkoutUrl":null}');

const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const path=()=>location.pathname.replace(/\/$/,'')||'/';
const productImage=slug=>shopifyProducts.find(p=>p.handle===slug)?.images?.edges?.[0]?.node?.url||'';
const shopifyProduct=slug=>shopifyProducts.find(p=>p.handle===slug);

async function shopify(query,variables={}){
  const r=await fetch(SHOPIFY_URL,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Storefront-Access-Token':SHOPIFY_TOKEN},body:JSON.stringify({query,variables})});
  if(!r.ok) throw new Error('The shop is temporarily unavailable. Please try again.');
  const json=await r.json(); if(json.errors?.length) throw new Error(json.errors[0].message); return json.data;
}
async function loadCatalog(){
  try{const d=await shopify(`query{products(first:40){edges{node{id handle title images(first:2){edges{node{url altText}}} variants(first:5){edges{node{id availableForSale price{amount currencyCode}}}}}}}}`);shopifyProducts=d.products.edges.map(x=>x.node);render();}catch(e){console.warn(e.message)}
}
const persist=()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount()};
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart.items.reduce((a,b)=>a+b.quantity,0))}

function shell(content){return `
  <a class="skip" href="#main">Skip to content</a>
  <header><a href="/" data-link class="wordmark">THE CAMILLE <i>LIBRARY</i></a><button class="menu" aria-label="Open menu">Menu</button><nav><a href="/library" data-link>Library</a><a href="/house" data-link>Business House</a><a href="/about" data-link>About</a></nav><a class="cart-link" href="/cart" data-link>Bag <span data-cart-count>0</span></a></header>
  <main id="main">${content}</main>
  <footer><div><a href="/" data-link class="wordmark light">THE CAMILLE <i>LIBRARY</i></a><p>Business, beautifully built.</p></div><div><b>Explore</b><a href="/library" data-link>The Library</a><a href="/house" data-link>Business House</a><a href="/about" data-link>Our Philosophy</a></div><div><b>Details</b><a href="/faq" data-link>FAQ</a><a href="/policies/privacy" data-link>Privacy</a><a href="/policies/terms" data-link>Terms</a><a href="/policies/refund" data-link>Refunds</a></div><p class="copyright">© ${new Date().getFullYear()} The Camille Library</p></footer>`}

function cover(p,large=false){const img=productImage(p.slug);return `<div class="cover ${large?'large':''}">${img?`<img src="${img}" alt="${p.title} cover"/>`:`<div class="cover-fallback"><small>THE CAMILLE LIBRARY</small><strong>${p.title}</strong><span>${p.category||'PRIVATE MEMBERSHIP'}</span></div>`}</div>`}
function productCard(p){return `<article class="product-card"><a href="/books/${p.slug}" data-link>${cover(p)}<div class="product-meta"><span>${p.category}</span><span>${money(p.price)}</span></div><h3>${p.title}</h3><p>${p.subtitle}</p><span class="text-link">Explore the system →</span></a></article>`}

function home(){const f=products[0];return shell(`
 <section class="hero"><div class="hero-copy"><p class="eyebrow">THE BUSINESS LIBRARY</p><h1>Business,<br><em>beautifully built.</em></h1><p class="lead">Clear systems for building a profitable business without building your life around chaos.</p><div class="actions"><a class="btn" href="/library" data-link>Browse the library</a></div></div><div class="hero-art">${cover(f,true)}<span class="edition">FEATURED · MONEY & PROFIT</span></div></section>
 <section class="featured"><div class="section-head"><div><p class="eyebrow">BEGIN HERE</p><h2>The essential systems.</h2></div><a href="/library" data-link>View the full library →</a></div><div class="grid">${products.slice(0,3).map(productCard).join('')}</div></section>
 <section class="house-band"><p class="eyebrow">THE PRIVATE MEMBERSHIP</p><h2>The Camille Business House</h2><p>Quarterly planning, implementation support, and thoughtful company for women building something substantial.</p><a class="btn cream" href="/house" data-link>Learn about the House</a></section>`)}

function library(){return shell(`<section class="page-intro"><p class="eyebrow">THE COMPLETE COLLECTION</p><h1>The Business Library</h1><p>Start with the constraint that is costing you the most — then choose the system designed to resolve it.</p></section><section class="catalog"><div class="filters"><button class="active" data-filter="all">All systems</button>${[...new Set(products.map(p=>p.category))].map(c=>`<button data-filter="${c}">${c}</button>`).join('')}</div><div class="grid" id="catalog-grid">${products.map(productCard).join('')}</div></section><section class="concierge"><p class="eyebrow">NOT SURE WHERE TO BEGIN?</p><h2>Name the bottleneck.</h2><p>If money feels foggy, begin with Wealth. If the offer is unclear, begin with Architecture. If the week keeps running you, begin with the Operating Desk.</p><a class="text-link" href="/contact" data-link>Ask for a recommendation →</a></section>`)}

function productPage(slug){const p=products.find(x=>x.slug===slug);if(!p)return notFound();return shell(`<section class="product-hero"><div>${cover(p,true)}</div><div class="product-copy"><p class="eyebrow">${p.category} · ${p.tier} EDITION</p><h1>${p.title}</h1><p class="subtitle">${p.subtitle}</p><p class="summary">${p.summary}</p><div class="buy-row"><strong>${money(p.price)}</strong><button class="btn" data-add="${p.slug}">Get instant access</button></div><div class="assurances"><span>Digital edition</span><span>Immediate delivery</span><span>Secure checkout</span></div><p class="micro">One-time purchase. Download instructions arrive after checkout.</p></div></section><section class="inside"><div><p class="eyebrow">THE TRANSFORMATION</p><h2>${p.outcome}</h2></div><div><p class="eyebrow">INSIDE THE EDITION</p><ul>${p.included.map(x=>`<li>${x}</li>`).join('')}</ul></div></section><section class="how"><p class="eyebrow">A SIMPLE WORKING RHYTHM</p><h2>Read it once.<br><em>Use it repeatedly.</em></h2><div class="steps"><div><span>01</span><h3>Decide</h3><p>Use the guided prompts to make the decisions that have been sitting open.</p></div><div><span>02</span><h3>Build</h3><p>Turn those decisions into one clear system for your business.</p></div><div><span>03</span><h3>Repeat</h3><p>Return to the framework whenever the business enters a new season.</p></div></div></section><section class="final-cta"><h2>Ready to put the system to work?</h2><button class="btn" data-add="${p.slug}">Get ${p.title} · ${money(p.price)}</button></section>`)}

function housePage(){return shell(`<section class="house-hero"><p class="eyebrow">A PRIVATE BUSINESS MEMBERSHIP · OPENING SOON</p><h1>The Camille<br><em>Business House</em></h1><p>Where good systems become the way you actually work. Quarterly planning, implementation sessions, fresh resources, and thoughtful company for women building something substantial.</p><div class="price-note"><strong>${money(house.price)}</strong><span>per month when doors open</span></div><a class="btn cream" href="/contact?subject=Business%20House" data-link>Join the private list</a><p class="micro light-text">No charge today. Private-list members hear first when enrollment opens.</p></section><section class="inside house-inside"><div><p class="eyebrow">INSIDE THE HOUSE</p><h2>Support with a point of view.</h2></div><div><ul><li>Quarterly planning sessions</li><li>Focused implementation rooms</li><li>New resources as the library grows</li><li>A considered member discussion space</li><li>Member pricing on new releases</li></ul></div></section>`)}

function about(){return shell(`<section class="page-intro about-intro"><p class="eyebrow">A NOTE FROM CAMILLE</p><h1>A beautiful business should also be a well-built one.</h1><p>I created The Camille Library for women whose ambition is substantial, but whose lives are not available for constant chaos. This is business education with standards: clear thinking, elegant tools, and systems built to be used after the excitement wears off.</p></section><section class="quote"><blockquote>“The goal is not to look busy. The goal is to build something that can hold your life.”</blockquote><span>— Camille Thomas, Founder</span></section><section class="about-grid"><div><p class="eyebrow">WHAT WE BELIEVE</p><h2>Calm is not the absence of ambition.</h2></div><div><p>It is what ambition feels like once the business has structure. The library exists to help you replace improvisation with principles, scattered effort with operating rhythms, and borrowed language with a position that is entirely your own.</p><a class="btn" href="/books/the-wealth-operating-system" data-link>Start with the Wealth System</a></div></section>`)}

function contact(){const q=new URLSearchParams(location.search);return shell(`<section class="page-intro"><p class="eyebrow">THE CONCIERGE DESK</p><h1>How can we help?</h1><p>Questions about an edition, your order, or where to begin? Send a note. We’ll point you in the right direction.</p></section><section class="contact-wrap"><form name="contact" method="POST" data-netlify="true" netlify-honeypot="company"><input type="hidden" name="form-name" value="contact"><p hidden class="honeypot"><label>Do not fill this out<input name="company"></label></p><label>Name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><label>Subject<input name="subject" value="${q.get('subject')||''}"></label><label>Message<textarea required name="message" rows="6"></textarea></label><button class="btn" type="submit">Send your note</button></form><aside><p class="eyebrow">BEFORE YOU WRITE</p><h3>Order support</h3><p>Include the email used at checkout so we can find your purchase quickly.</p><h3>Choosing a system</h3><p>Tell us what feels stuck. We’ll recommend the most useful place to begin.</p></aside></section>`)}

function faq(){return shell(`<section class="page-intro"><p class="eyebrow">THE DETAILS</p><h1>Frequently asked questions</h1></section><section class="faqs">${[['What am I purchasing?','Each library edition is a digital business system delivered electronically. The Business House is separate: it is a forthcoming monthly membership, and joining its private list does not charge you.'],['How do I receive my purchase?','After secure Shopify checkout, you will receive delivery instructions at the email address used for your order.'],['Can I get a refund?','Because digital files are delivered immediately, purchases are generally final. If a file is defective or you cannot access it, contact us so we can make it right.'],['Which system should I begin with?','Start with the most expensive constraint. Money fog: Wealth Operating System. An unclear offer: Premium Offer Architect. An unmanageable week: Solo CEO Operating Desk.'],['May I share the files?','Your purchase is licensed for your personal business use. Please do not distribute, resell, reproduce, or upload the materials elsewhere.']].map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</section>`)}

function policy(kind){const data={privacy:['Privacy Policy','We collect the information you provide at checkout or through our contact form to fulfill orders, provide support, and communicate with you. Payments are processed by Shopify and its payment providers; we do not store full payment card details. We use reasonable safeguards and only retain information as long as needed for business, legal, or security purposes. You may request access, correction, or deletion of your personal information by contacting us.'],terms:['Terms of Use','The Camille Library provides educational digital materials and does not provide legal, tax, accounting, investment, or financial advice. Purchases grant one person a limited, non-transferable license for personal business use. You may not resell, share, reproduce, or distribute the materials. Product descriptions and availability may change. By using this site, you agree to use the materials lawfully and accept responsibility for your own business decisions.'],refund:['Digital Product & Refund Policy','Digital editions are delivered electronically and are generally non-refundable once access has been provided. If you receive a defective file, duplicate charge, or cannot access your purchase, contact us with your order email and we will work to correct the problem. Membership terms and cancellation details will be presented separately before the Business House opens.']};const [title,body]=data[kind]||data.terms;return shell(`<section class="policy"><p class="eyebrow">LAST UPDATED SEPTEMBER 2026</p><h1>${title}</h1>${body.split('. ').map(x=>`<p>${x}${x.endsWith('.')?'':'.'}</p>`).join('')}<p>Questions may be sent through our <a href="/contact" data-link>contact page</a>.</p></section>`)}

function cartPage(){const total=cart.items.reduce((s,i)=>s+i.price*i.quantity,0);return shell(`<section class="page-intro"><p class="eyebrow">YOUR SELECTIONS</p><h1>The reading bag</h1></section><section class="cart-page">${cart.items.length?`<div class="cart-items">${cart.items.map(i=>`<article>${cover(i)}<div><p class="eyebrow">DIGITAL EDITION</p><h3>${i.title}</h3><span>${money(i.price)}</span></div><button aria-label="Remove ${i.title}" data-remove="${i.slug}">Remove</button></article>`).join('')}</div><aside class="order"><p>Order total <strong>${money(total)}</strong></p><button class="btn" id="checkout">Proceed to secure checkout</button><small>Checkout is securely processed by Shopify.</small><p class="error" id="cart-error"></p></aside>`:`<div class="empty"><h2>Your bag is quiet.</h2><p>Choose the system that resolves the clearest constraint in your business.</p><a class="btn" href="/library" data-link>Browse the library</a></div>`}</section>`)}

function notFound(){return shell(`<section class="page-intro"><p class="eyebrow">PAGE NOT FOUND</p><h1>This title is no longer on the shelf.</h1><p>The library has been reorganized. Browse the current collection to find the right system.</p><a class="btn" href="/library" data-link>View the library</a></section>`)}
function render(){const p=path();let html=p==='/'?home():p==='/library'?library():p==='/house'?housePage():p==='/about'?about():p==='/contact'?contact():p==='/faq'?faq():p==='/cart'?cartPage():p.startsWith('/books/')?productPage(p.split('/').pop()):p.startsWith('/policies/')?policy(p.split('/').pop()):notFound();$('#app').innerHTML=html;bind();updateCartCount();window.scrollTo(0,0)}
function go(url){history.pushState({},'',url);render()}

async function addItem(slug){const p=products.find(x=>x.slug===slug);const sp=shopifyProduct(slug);const variant=sp?.variants?.edges?.map(x=>x.node).find(x=>x.availableForSale)||sp?.variants?.edges?.[0]?.node;if(!variant){alert('This edition is temporarily unavailable. Please contact us for help.');return}const old=cart.items.find(i=>i.slug===slug);if(old){old.quantity+=1}else{cart.items.push({...p,quantity:1,variantId:variant.id,image:productImage(slug)})}persist();go('/cart')}
async function checkout(){const btn=$('#checkout'),err=$('#cart-error');btn.disabled=true;btn.textContent='Preparing checkout…';err.textContent='';try{const lines=cart.items.map(i=>({quantity:i.quantity,merchandiseId:i.variantId}));const data=await shopify(`mutation CreateCart($input:CartInput!){cartCreate(input:$input){cart{id checkoutUrl} userErrors{message}}}`,{input:{lines}});const result=data.cartCreate;if(result.userErrors?.length)throw new Error(result.userErrors.map(x=>x.message).join(', '));if(!result.cart?.checkoutUrl)throw new Error('Checkout could not be created.');cart.cartId=result.cart.id;cart.checkoutUrl=result.cart.checkoutUrl;persist();location.assign(result.cart.checkoutUrl)}catch(e){err.textContent=e.message;btn.disabled=false;btn.textContent='Proceed to secure checkout'}}
function bind(){document.querySelectorAll('a[data-link]').forEach(a=>a.addEventListener('click',e=>{if(!e.metaKey&&!e.ctrlKey){e.preventDefault();go(a.getAttribute('href'))}}));$('.menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addItem(b.dataset.add)));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.items=cart.items.filter(i=>i.slug!==b.dataset.remove);persist();render()}));$('#checkout')?.addEventListener('click',checkout);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#catalog-grid').innerHTML=products.filter(p=>f==='all'||p.category===f).map(productCard).join('');bind()}))}
window.addEventListener('popstate',render);render();loadCatalog();
