import './styles.css';

const SHOPIFY_URL = 'https://brand-blueprint-studio-wt3ml-abpg4kjq.myshopify.com/api/2025-07/graphql.json';
const SHOPIFY_TOKEN = 'bfedf7bb47b55313afd3bdbc34af856a';
const CART_KEY = 'camille-cart-v3';

const products = [
  {slug:'the-wealth-operating-system',title:'The Wealth Operating System',subtitle:'The weekly money rhythm behind a business that can actually fund your life.',category:'Capital & Profit',tier:'Signature',price:39,summary:'A complete operating rhythm for personal and business money, so income stops disappearing into guesswork.',included:['The weekly money meeting framework','Income, commitments, and reserves map','Lifestyle affordability worksheet','Spending decision rules','Ninety-day money rhythm tracker'],outcome:'Know what came in, what is committed, what is protected, and what your next financial decision should be.'},
  {slug:'the-profit-clarity-planner',title:'The Profit Clarity Planner',subtitle:'Revenue, costs, reserves, owner pay, and profit in language you can act on.',category:'Capital & Profit',tier:'Foundation',price:29,summary:'A guided planner that turns business numbers into five clear figures you can review in an afternoon.',included:['Five-figure profit worksheet','Cost of delivery breakdown','Reserve and tax holding guide','Owner pay planner','Quarterly profit review sheet'],outcome:'Leave with a completed profit picture and a defensible owner-pay number.'},
  {slug:'the-premium-offer-architect',title:'The Premium Offer Architect',subtitle:'Turn scattered skill into one focused offer you can explain in a sentence.',category:'Offers & Assets',tier:'Signature',price:79,summary:'A structured method for shaping one clear, sellable offer instead of ten half-built ideas.',included:['Buyer fit map','Transformation ladder','Offer architecture canvas','Scope control checklist','Pricing rationale worksheet'],outcome:'Define one premium offer with a clear buyer, transformation, scope, and price.'},
  {slug:'brand-with-weight',title:'Brand With Weight',subtitle:'Positioning, voice, and visual direction that make the business unmistakable.',category:'Authority & Demand',tier:'Signature',price:89,summary:'A brand system for women whose thinking is stronger than the way the business currently communicates it.',included:['Brand thesis workbook','Positioning statement builder','Signature method canvas','Voice and language guide','Visual direction board'],outcome:'Build a brand that reads as considered, consistent, and distinctly yours.'},
  {slug:'the-digital-product-studio',title:'The Digital Product Studio',subtitle:'Plan, build, and finish a digital product without losing months to it.',category:'Offers & Assets',tier:'Essential',price:59,summary:'A production system for turning knowledge into an ebook, workbook, toolkit, or mini course that actually ships.',included:['Format selection guide','Product outline builder','Production sequence plan','Asset and template checklist','Delivery and file setup guide'],outcome:'Move from a strong idea to a finished, deliverable digital product.'},
  {slug:'the-signature-content-system',title:'The Signature Content System',subtitle:'Content that connects to the offer instead of feeding the algorithm.',category:'Authority & Demand',tier:'Essential',price:49,summary:'A content system built around themes, customer journey, and the offer you are actually selling.',included:['Content pillar builder','Buyer journey map','Signature idea bank','Monthly content rhythm planner','Call-to-action library'],outcome:'Publish fewer, better-placed ideas that lead naturally to your offer.'},
  {slug:'the-calm-launch-playbook',title:'The Calm Launch Playbook',subtitle:'A composed launch with real messaging, timing, and a proper review afterwards.',category:'Revenue',tier:'Signature',price:69,summary:'A full launch plan built on preparation and clear messaging rather than urgency and noise.',included:['Launch runway timeline','Messaging and angle planner','Email sequence outlines','Daily launch-week schedule','Post-launch review framework'],outcome:'Run a repeatable launch without panic, improvisation, or borrowed urgency.'},
  {slug:'the-elevated-sales-page-kit',title:'The Elevated Sales Page Kit',subtitle:'Write a product page that communicates value without a single hype line.',category:'Revenue',tier:'Foundation',price:39,summary:'Section-by-section structure and language for a sales page that reads as premium and converts.',included:['Page structure blueprint','Section-by-section prompts','Objection handling bank','Headline patterns','Pre-publish review checklist'],outcome:'Draft a complete sales page that answers the buyer’s questions in the right order.'},
  {slug:'the-solo-ceo-operating-desk',title:'The Solo CEO Operating Desk',subtitle:'Weekly priorities, delivery, sales, and customer care in one calm structure.',category:'Operations',tier:'Signature',price:79,summary:'The operating structure for a woman running everything herself and wanting the week to hold.',included:['Weekly operating rhythm planner','Priority and capacity sheet','Delivery workflows','Customer care standards guide','Monthly business review'],outcome:'Give every essential part of the business a place in the week.'},
];
const house={slug:'the-camille-business-house',title:'The Camille Business House',subtitle:'Ongoing implementation, planning, and company for women building something substantial.',price:29};
let shopifyProducts=[];
let cart=JSON.parse(localStorage.getItem(CART_KEY)||'{"items":[],"cartId":null,"checkoutUrl":null}');

const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const path=()=>location.pathname.replace(/\/$/,'')||'/';
const productImage=slug=>shopifyProducts.find(p=>p.handle===slug)?.images?.edges?.[0]?.node?.url||'';
const shopifyProduct=slug=>shopifyProducts.find(p=>p.handle===slug);

async function shopify(query,variables={}){
  const r=await fetch(SHOPIFY_URL,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Storefront-Access-Token':SHOPIFY_TOKEN},body:JSON.stringify({query,variables})});
  if(!r.ok) throw new Error('The shop is temporarily unavailable. Please try again.');
  const json=await r.json(); if(json.errors?.length) throw new Error(json.errors[0].message); return json.data;
}
async function loadCatalog(){
  try{const d=await shopify(`query{products(first:40){edges{node{id handle title images(first:2){edges{node{url altText}}} variants(first:5){edges{node{id availableForSale price{amount currencyCode}}}}}}}}`);shopifyProducts=d.products.edges.map(x=>x.node);render();}catch(e){console.warn(e.message)}
}
const persist=()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount()};
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart.items.reduce((a,b)=>a+b.quantity,0))}

function shell(content){return `
  <a class="skip" href="#main">Skip to content</a>
  <header>
    <a href="/" data-link class="wordmark"><span>THE CAMILLE</span><i>LIBRARY</i></a>
    <button class="menu" aria-label="Open menu">Menu</button>
    <nav><a href="/library" data-link>Editions</a><a href="/house" data-link>The House</a><a href="/about" data-link>Maison</a></nav>
    <a class="cart-link" href="/cart" data-link>Selection <span data-cart-count>0</span></a>
  </header>
  <main id="main">${content}</main>
  <footer>
    <div class="footer-mark"><a href="/" data-link class="wordmark light"><span>THE CAMILLE</span><i>LIBRARY</i></a><p>Private editions for the business of wealth.</p></div>
    <div><b>The Library</b><a href="/library" data-link>All editions</a><a href="/house" data-link>The Business House</a><a href="/about" data-link>Our point of view</a></div>
    <div><b>Client services</b><a href="/contact" data-link>Private concierge</a><a href="/faq" data-link>Information</a><a href="/policies/privacy" data-link>Privacy</a><a href="/policies/terms" data-link>Terms</a></div>
    <p class="copyright">© ${new Date().getFullYear()} The Camille Library · Camille Thomas</p>
  </footer>`}

function cover(p,large=false){const img=productImage(p.slug);return `<figure class="cover ${large?'large':''}">${img?`<img src="${img}" alt="${p.title} cover"/>`:`<div class="cover-fallback"><small>THE CAMILLE LIBRARY</small><strong>${p.title}</strong><span>${p.category||'PRIVATE MEMBERSHIP'}</span></div>`}</figure>`}
function productCard(p,i=0){return `<article class="product-card"><a href="/books/${p.slug}" data-link><span class="folio">${String(i+1).padStart(2,'0')}</span>${cover(p)}<div class="product-card-copy"><div class="product-meta"><span>${p.category}</span><span>${money(p.price)}</span></div><h3>${p.title}</h3><p>${p.subtitle}</p><span class="text-link">Enter the edition</span></div></a></article>`}

function home(){const f=products[0];return shell(`
  <section class="hero">
    <div class="hero-copy"><p class="eyebrow">VOLUME I · THE BUSINESS OF WEALTH</p><h1>Private systems.<br><em>Public ambition.</em></h1><p class="lead">The Camille Library publishes rigorous, beautifully composed business systems for women turning expertise into assets, profit, and ownership.</p><a class="arrow-link" href="/library" data-link>Enter the library <span>↗</span></a></div>
    <div class="hero-art"><span class="hero-note">THE SIGNATURE EDITION</span>${cover(f,true)}<p>Structure your money.<br>Fund your life.</p></div>
    <div class="hero-index"><span>EST. 2026</span><span>DALLAS · DIGITAL</span><span>01 / 09</span></div>
  </section>
  <section class="thesis"><p class="eyebrow">THE LIBRARY THESIS</p><h2>A serious business deserves more than scattered advice.</h2><p>Every edition resolves one consequential constraint—money, offer, authority, revenue, or operations—and leaves you with a system worth returning to.</p></section>
  <section class="selected"><div class="section-head"><div><p class="eyebrow">CURATED FIRST</p><h2>Three places to begin.</h2></div><a class="arrow-link dark" href="/library" data-link>View all nine <span>↗</span></a></div><div class="editorial-list">${products.slice(0,3).map(productCard).join('')}</div></section>
  <section class="house-band"><div><p class="eyebrow">THE PRIVATE ROOM</p><h2>The Camille<br><em>Business House</em></h2></div><div><p>For women ready to apply the work in thoughtful company. Planning, implementation, and a room with standards.</p><a class="arrow-link light" href="/house" data-link>Request first access <span>↗</span></a></div></section>`)}

function library(){return shell(`<section class="page-intro library-intro"><p class="eyebrow">THE COMPLETE CATALOGUE · NINE EDITIONS</p><h1>The business<br>of wealth.</h1><p>A private reference library for the decisions beneath a profitable company.</p></section><section class="catalog"><div class="filters"><button class="active" data-filter="all">Complete catalogue</button>${[...new Set(products.map(p=>p.category))].map(c=>`<button data-filter="${c}">${c}</button>`).join('')}</div><div class="editorial-list" id="catalog-grid">${products.map(productCard).join('')}</div></section><section class="concierge"><p class="eyebrow">PRIVATE CONCIERGE</p><h2>Choose the constraint,<br>not the prettiest cover.</h2><p>Money fog: begin with Wealth. An unclear offer: begin with Architecture. An unmanageable week: begin with the Operating Desk.</p><a class="arrow-link dark" href="/contact" data-link>Request a recommendation <span>↗</span></a></section>`)}

function productPage(slug){const p=products.find(x=>x.slug===slug);if(!p)return notFound();const number=String(products.indexOf(p)+1).padStart(2,'0');return shell(`<section class="product-hero"><div class="product-stage"><span class="vertical-type">THE CAMILLE LIBRARY · EDITION ${number}</span>${cover(p,true)}</div><div class="product-copy"><p class="eyebrow">${p.category} · ${p.tier} EDITION</p><h1>${p.title}</h1><p class="subtitle">${p.subtitle}</p><p class="summary">${p.summary}</p><div class="buy-row"><strong>${money(p.price)}</strong><button class="btn" data-add="${p.slug}">Acquire the edition</button></div><p class="micro">Digital edition · one-time purchase · secure Shopify checkout</p></div></section><section class="inside"><div><p class="eyebrow">THE RESULT</p><h2>${p.outcome}</h2></div><div><p class="eyebrow">THE CONTENTS</p><ol>${p.included.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${x}</li>`).join('')}</ol></div></section><section class="how"><p class="eyebrow">THE METHOD</p><h2>Not more information.<br><em>A way of operating.</em></h2><div class="steps"><div><span>01</span><h3>Decide</h3><p>Close the decisions that have been quietly draining the business.</p></div><div><span>02</span><h3>Build</h3><p>Turn those decisions into a structure you can actually use.</p></div><div><span>03</span><h3>Return</h3><p>Revisit the system as the company enters its next season.</p></div></div></section><section class="final-cta"><p class="eyebrow">EDITION ${number}</p><h2>${p.title}</h2><button class="btn inverse" data-add="${p.slug}">Acquire · ${money(p.price)}</button></section>`)}

function housePage(){return shell(`<section class="house-hero"><p class="eyebrow">BY PRIVATE LIST · OPENING SOON</p><h1>The room<br>behind the work.</h1><p>The Camille Business House is where the library becomes practice: planning, implementation, and thoughtful company for women building something substantial.</p><a class="arrow-link light" href="/contact?subject=Business%20House" data-link>Request first access <span>↗</span></a><div class="price-note"><strong>${money(house.price)}</strong><span>monthly when the doors open · no charge today</span></div></section><section class="inside house-inside"><div><p class="eyebrow">THE HOUSE STANDARD</p><h2>Quiet rooms.<br>Serious work.</h2></div><div><ol><li><span>01</span>Quarterly planning salons</li><li><span>02</span>Focused implementation rooms</li><li><span>03</span>New private library resources</li><li><span>04</span>Considered member discussion</li><li><span>05</span>Member privileges on releases</li></ol></div></section>`)}

function about(){return shell(`<section class="page-intro about-intro"><p class="eyebrow">THE MAISON · FOUNDED BY CAMILLE THOMAS</p><h1>Wealth should be built with clarity—not performed for attention.</h1><p>The Camille Library exists for women whose expertise deserves an architecture: durable income, protected profit, and ownership that can outlast a season online.</p></section><section class="quote"><span>THE FOUNDING PRINCIPLE</span><blockquote>Build the structure first.<br>The scale can follow.</blockquote></section><section class="about-grid"><div><p class="eyebrow">OUR EDITORIAL STANDARD</p><h2>Fewer ideas.<br>Better decisions.</h2></div><div><p>We publish only what helps a woman make a consequential business decision, construct the system beneath it, and return to that system as her company grows.</p><a class="arrow-link light" href="/books/the-wealth-operating-system" data-link>Read the Signature Edition <span>↗</span></a></div></section>`)}

function contact(){const q=new URLSearchParams(location.search);return shell(`<section class="page-intro"><p class="eyebrow">LIBRARY CONCIERGE</p><h1>How may we help?</h1><p>For guidance choosing an edition or assistance with an order, send a private note.</p></section><section class="contact-wrap"><form name="contact" method="POST" data-netlify="true" netlify-honeypot="company"><input type="hidden" name="form-name" value="contact"><p hidden class="honeypot"><label>Do not fill this out<input name="company"></label></p><label>Name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><label>Subject<input name="subject" value="${q.get('subject')||''}"></label><label>Message<textarea required name="message" rows="6"></textarea></label><button class="btn" type="submit">Send your note</button></form><aside><p class="eyebrow">BEFORE YOU WRITE</p><h3>Order support</h3><p>Include the email used at checkout so we can find your purchase quickly.</p><h3>Choosing a system</h3><p>Tell us what feels stuck. We’ll recommend the most useful place to begin.</p></aside></section>`)}

function faq(){return shell(`<section class="page-intro"><p class="eyebrow">THE DETAILS</p><h1>Frequently asked questions</h1></section><section class="faqs">${[['What am I purchasing?','Each library edition is a digital business system delivered electronically. The Business House is separate: it is a forthcoming monthly membership, and joining its private list does not charge you.'],['How do I receive my purchase?','After secure Shopify checkout, you will receive delivery instructions at the email address used for your order.'],['Can I get a refund?','Because digital files are delivered immediately, purchases are generally final. If a file is defective or you cannot access it, contact us so we can make it right.'],['Which system should I begin with?','Start with the most expensive constraint. Money fog: Wealth Operating System. An unclear offer: Premium Offer Architect. An unmanageable week: Solo CEO Operating Desk.'],['May I share the files?','Your purchase is licensed for your personal business use. Please do not distribute, resell, reproduce, or upload the materials elsewhere.']].map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</section>`)}

function policy(kind){const data={privacy:['Privacy Policy','We collect the information you provide at checkout or through our contact form to fulfill orders, provide support, and communicate with you. Payments are processed by Shopify and its payment providers; we do not store full payment card details. We use reasonable safeguards and only retain information as long as needed for business, legal, or security purposes. You may request access, correction, or deletion of your personal information by contacting us.'],terms:['Terms of Use','The Camille Library provides educational digital materials and does not provide legal, tax, accounting, investment, or financial advice. Purchases grant one person a limited, non-transferable license for personal business use. You may not resell, share, reproduce, or distribute the materials. Product descriptions and availability may change. By using this site, you agree to use the materials lawfully and accept responsibility for your own business decisions.'],refund:['Digital Product & Refund Policy','Digital editions are delivered electronically and are generally non-refundable once access has been provided. If you receive a defective file, duplicate charge, or cannot access your purchase, contact us with your order email and we will work to correct the problem. Membership terms and cancellation details will be presented separately before the Business House opens.']};const [title,body]=data[kind]||data.terms;return shell(`<section class="policy"><p class="eyebrow">LAST UPDATED SEPTEMBER 2026</p><h1>${title}</h1>${body.split('. ').map(x=>`<p>${x}${x.endsWith('.')?'':'.'}</p>`).join('')}<p>Questions may be sent through our <a href="/contact" data-link>contact page</a>.</p></section>`)}

function cartPage(){const total=cart.items.reduce((s,i)=>s+i.price*i.quantity,0);return shell(`<section class="page-intro"><p class="eyebrow">YOUR SELECTIONS</p><h1>The reading bag</h1></section><section class="cart-page">${cart.items.length?`<div class="cart-items">${cart.items.map(i=>`<article>${cover(i)}<div><p class="eyebrow">DIGITAL EDITION</p><h3>${i.title}</h3><span>${money(i.price)}</span></div><button aria-label="Remove ${i.title}" data-remove="${i.slug}">Remove</button></article>`).join('')}</div><aside class="order"><p>Order total <strong>${money(total)}</strong></p><button class="btn" id="checkout">Proceed to secure checkout</button><small>Checkout is securely processed by Shopify.</small><p class="error" id="cart-error"></p></aside>`:`<div class="empty"><h2>Your bag is quiet.</h2><p>Choose the system that resolves the clearest constraint in your business.</p><a class="btn" href="/library" data-link>Browse the library</a></div>`}</section>`)}

function notFound(){return shell(`<section class="page-intro"><p class="eyebrow">PAGE NOT FOUND</p><h1>This title is no longer on the shelf.</h1><p>The library has been reorganized. Browse the current collection to find the right system.</p><a class="btn" href="/library" data-link>View the library</a></section>`)}
function render(){const p=path();let html=p==='/'?home():p==='/library'?library():p==='/house'?housePage():p==='/about'?about():p==='/contact'?contact():p==='/faq'?faq():p==='/cart'?cartPage():p.startsWith('/books/')?productPage(p.split('/').pop()):p.startsWith('/policies/')?policy(p.split('/').pop()):notFound();$('#app').innerHTML=html;bind();updateCartCount();window.scrollTo(0,0)}
function go(url){history.pushState({},'',url);render()}

async function addItem(slug){const p=products.find(x=>x.slug===slug);const sp=shopifyProduct(slug);const variant=sp?.variants?.edges?.map(x=>x.node).find(x=>x.availableForSale)||sp?.variants?.edges?.[0]?.node;if(!variant){alert('This edition is temporarily unavailable. Please contact us for help.');return}const old=cart.items.find(i=>i.slug===slug);if(old){old.quantity+=1}else{cart.items.push({...p,quantity:1,variantId:variant.id,image:productImage(slug)})}persist();go('/cart')}
async function checkout(){const btn=$('#checkout'),err=$('#cart-error');btn.disabled=true;btn.textContent='Preparing checkout…';err.textContent='';try{const lines=cart.items.map(i=>({quantity:i.quantity,merchandiseId:i.variantId}));const data=await shopify(`mutation CreateCart($input:CartInput!){cartCreate(input:$input){cart{id checkoutUrl} userErrors{message}}}`,{input:{lines}});const result=data.cartCreate;if(result.userErrors?.length)throw new Error(result.userErrors.map(x=>x.message).join(', '));if(!result.cart?.checkoutUrl)throw new Error('Checkout could not be created.');cart.cartId=result.cart.id;cart.checkoutUrl=result.cart.checkoutUrl;persist();location.assign(result.cart.checkoutUrl)}catch(e){err.textContent=e.message;btn.disabled=false;btn.textContent='Proceed to secure checkout'}}
function bind(){document.querySelectorAll('a[data-link]').forEach(a=>a.addEventListener('click',e=>{if(!e.metaKey&&!e.ctrlKey){e.preventDefault();go(a.getAttribute('href'))}}));$('.menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addItem(b.dataset.add)));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.items=cart.items.filter(i=>i.slug!==b.dataset.remove);persist();render()}));$('#checkout')?.addEventListener('click',checkout);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;$('#catalog-grid').innerHTML=products.filter(p=>f==='all'||p.category===f).map(productCard).join('');bind()}))}
window.addEventListener('popstate',render);render();loadCatalog();
